### ISSUE TITLE
[meta] Reinstate RFCs / CEPs for major items

### ISSUE THREAD

**Issue by rufuspollock** [ckan/ideas#83]
We want a simple process and format for proposing significant new improvements and changes to CKAN. The idea is to use something RFC-like.

For more information on RFCs and structure see http://playbook.datopian.com/how-to-propose-changes/ See also https://github.com/vuejs/rfcs

## Acceptance

* [ ] RFC process detailed in this repo README
* [x] RFC template and folder

## Tasks

* [x] Move `/specs/` to `/rfcs/`
* [x] Create a template file in the root of the repo
* [ ] Explain about RFCs in the README
  * [ ] Info on the process ...
* [ ] Announced (?)

## Original - Sep 2014

CEPs = CKAN Enhancement Proposals like PEPs but for CKAN (we used to have these a couple of years ago and I can dig out the old repo)

What: for larger proposals, once we've established their is a bit of interest we boot a small markdown document in the CEP repo and the proposal gets developed there. (As an example see the [OSEP (OpenSpending Enhancement Proposal) repo](https://github.com/openspending/osep/)).

Why: provides a structured way to develop larger proposals and to track (and refer to) them over time. Drafting larger docs is not so good in github issues (esp as comments go out of date as main body of issue changes). Also the slightly more formal process can lead to more detailed and more worked out proposals.

Why Not: why not just use issues here (you can do markdown).

**Comment by rufuspollock** [comment]
Flagging this as something to actively reinstate now 😄

**Comment by rufuspollock** [comment]
I note vuejs have rfcs - https://github.com/vuejs/rfcs/ (might be a nicer name).
